version: 2
jobs:
        build:
                docker:
                        - image: node:8.0
                steps:
                        - run:
                                name: "Checking Version"
                                command: |
                                        node --version
                                        npm --version
