version: 2
jobs:
        build:
                docker:
                        - image: node:8.0
                steps:
                        - run: |
                                node --version
                                npm --version
                        - checkout
        test:
                docker:
                        - image: node:8.0
                test:
                        - checkout
                        - run: mkdir test; mkdir ./test/react ; mv * ./test/react/ ; echo '{"clientId": "${CLIENT_ID}",apiKey": "${API_KEY}","scope": "https://www.googleapis.com/auth/calendar","discoveryDocs":"https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"]}' > ./apiGoogleconfig.json

                        - run: cd test/react ; npm run test

workflows:
        version: 2
        build_and_test:
                jobs:
                        - build
                        - test
